export const RESET_CONTACT_US_STATE = 'RESET_CONTACT_US_STATE';

// CONTACT US
export const API_CONTACT_US_REQUEST = 'API_CONTACT_US_REQUEST';
export const API_CONTACT_US_REQUEST_SUCCESS = 'API_CONTACT_US_REQUEST_SUCCESS';
export const API_CONTACT_US_REQUEST_FAILED = 'API_CONTACT_US_REQUEST_FAILED';
