// LOGIN
export const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
export const API_LOGIN_REQUEST_SUCCESS = 'API_LOGIN_REQUEST_SUCCESS';
export const API_LOGIN_REQUEST_FAILED = 'API_LOGIN_REQUEST_FAILED';
