// SIGNUP
export const API_SIGNUP_REQUEST = 'API_SIGNUP_REQUEST';
export const API_SIGNUP_REQUEST_SUCCESS = 'API_SIGNUP_REQUEST_SUCCESS';
export const API_SIGNUP_REQUEST_FAILED = 'API_SIGNUP_REQUEST_FAILED';
